### ISSUE TITLE
Delete Lines

### ISSUE THREAD

**Issue by itjunkii83** [wangshengjia/XcodeEditorPlus#3]
Hello,

Thanks for making this example. I found a bug when you highlight any number of characters in a line and then execute delete line I get a crash. If you don't highlight before executing it works fine.

Application Specific Information:
ProductBuildVersion: 8B62
UNCAUGHT EXCEPTION (NSInvalidArgumentException): *** +[NSSelectionArray newWithArray:]: no ranges
UserInfo: (null)
Hints: None
Backtrace:
  0   __exceptionPreprocess (in CoreFoundation)
  1   DVTFailureHintExceptionPreprocessor (in DVTFoundation)
  2   objc_exception_throw (in libobjc.A.dylib)
  3   +[NSException raise:format:] (in CoreFoundation)
  4   +[NSSelectionArray newWithArray:] (in AppKit)
  5   +[NSSelectionArray arrayWithArray:] (in AppKit)

**Comment by wangshengjia** [comment]
Thank you for reporting, I'll looking into this later.

**Comment by wangshengjia** [comment]
Fixed by #4
